import { lazy } from 'react';

export const moduleRoutes = [
  {
    path: '/linear-regression',
    component: lazy(() => import('../modules/linear-regression/LinearRegressionPage')),
    title: 'Linear Regression',
    description:
      'Drag points to create data, watch a line fit in real-time using gradient descent.',
    difficulty: 'beginner' as const,
    icon: 'TrendingUp',
    tech: 'TF.js',
  },
  {
    path: '/kmeans',
    component: lazy(() => import('../modules/kmeans/KMeansPage')),
    title: 'K-Means Clustering',
    description: 'Place data points and watch centroids converge step by step.',
    difficulty: 'beginner' as const,
    icon: 'Layers',
    tech: 'Pure TS',
  },
  {
    path: '/gradient-descent',
    component: lazy(() => import('../modules/gradient-descent/GradientDescentPage')),
    title: 'Gradient Descent',
    description: 'Explore a 3D loss surface and watch gradient descent find the minimum.',
    difficulty: 'intermediate' as const,
    icon: 'Mountain',
    tech: 'Three.js',
  },
  {
    path: '/neural-network',
    component: lazy(() => import('../modules/neural-network/NeuralNetworkPage')),
    title: 'Neural Network',
    description: 'Build and train neural networks, visualize decision boundaries in real-time.',
    difficulty: 'intermediate' as const,
    icon: 'Brain',
    tech: 'TF.js',
  },
  {
    path: '/image-classification',
    component: lazy(() => import('../modules/image-classification/ImageClassificationPage')),
    title: 'Image Classification',
    description: 'Classify images using MobileNet — upload a photo or use your webcam.',
    difficulty: 'beginner' as const,
    icon: 'Image',
    tech: 'MobileNet',
  },
  {
    path: '/transfer-learning',
    component: lazy(() => import('../modules/transfer-learning/TransferLearningPage')),
    title: 'Transfer Learning',
    description: 'Retrain MobileNet to recognize your own custom categories using webcam samples.',
    difficulty: 'advanced' as const,
    icon: 'Repeat',
    tech: 'TF.js',
  },
  {
    path: '/cnn-visualization',
    component: lazy(() => import('../modules/cnn-visualization/CNNVisualizationPage')),
    title: 'CNN Visualization',
    description: 'See inside a convolutional neural network — filter weights and activation maps.',
    difficulty: 'advanced' as const,
    icon: 'Eye',
    tech: 'MobileNet',
  },
  {
    path: '/llm',
    component: lazy(() => import('../modules/llm/LLMPage')),
    title: 'LLM Playground',
    description: 'Chat with an LLM running entirely in your browser. Explore tokens and sampling.',
    difficulty: 'advanced' as const,
    icon: 'MessageSquare',
    tech: 'WebLLM',
  },
];
